sudo: false

language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

install: mvn -B install -U -DskipTests=true

script: mvn -B verify -U -Dmaven.javadoc.skip=true

after_success:
  - util/deploy_snapshot.sh
  - util/update_snapshot_docs.sh

cache:
  directories:
  - $HOME/.m2

global:
  - secure: NAS6c+qLypygToua5OAm4FPsZDX95fbubpPHxSInTAAo16Bbg3diIF5vXJddhWeyadiAOTpg38LTfzrXiNg4QVtqWFL2FpGQ1sv3xdEuUfBwVtYLEDHEzqJ1gQxQy6NpIsV7QKV6bX1NoM6yvuwdXj7N7mvLaIFrEkeqe4N8jaHN9RpZT1UpPQmiMekLISnbWT7VjgZlVjM0ZmA2DIxsUwJlVwOoIiUlHxpJMiu7PW+NPAlMbilDowiifjkdRVeMxEiVFPvd61QD1+ReQ1lIVRStIlHJ0E3Qxs7n6QN1MStqXlQI7djBVkzQoc/g7nZAm1/89O/u4NP59rLmYHkD7Wrd+rQK335zfGBZfzobt5xCajD6Z1iu6gljURCeE+awZrnkdZ1/Zz8priXagw/Rzl2arLrT5qGzor4h9C1IwM2GBzfK1A7yYEJYy4wtxuPVk0+6vrHAICrwo1GgA0gru7lW7wI6S1X9E7TKhKBTHN0QSRUaiEAQwlzfjB53A1wMCnXLM7wG/Nz3yTmmGkF6eeJjlviajDbwE7gaiHYrue8FIKdIMZxP1o5gcOeSfcL3gZlgnyHq5BckctSRZMzzveXdRLME+8wcVV36DTJrgBY4zZp3zb43zsXQbEWo2D0ZlcVsHuWZm4T48ob/KLjE5S3oln08mvHWbCE0hUfKfiU=

env:
  global:
    - secure: "IPvqFwnLx/GXyImJuwM2MIvzDlBLqEXaQXFGJgAP1nbuenaLAloOOlqQ+iy2FDLBD/j+zjSbR3WWF9DIT4YxAS03Z6iMwxh7GCfk+tyhVtLQnwt7w1rquyhbrrGFsY5U0hr5q80Ww6J+zfp2yZ8aP9FHSy5ahNjqys4FtubOWLk="
    - secure: "G77Wt2h2fceQ867i1uwOjUygrNeBpLRS8sxgfUZsO66dvlrx1wYFpZLLRIiPcy01peUTE2SvXIXLHKe9v3AlMonPibsQtvvfQSVfx+jgKwLZx9cuf/M5VQlD3etRUh4K/rBezlxWRroeeKcM2DQqiEVLsTDSyNZV9kVAjwfLTvM="
    - secure: "wieIClPLTXS3QjDzqyp0TqIrVP/Q6iWNPOtcUQYfdDZJGwufE61laTFtzVKXZRb7uJ4GXDObcVU3AcpAwkTX/5sEksBxgv3TZ5Qi0mVx2GRmbE06ULLxi7sPnTCZ/VFtselDWcWArWGAcdCjW9gcCrgj5K/+sYpVKz9a8V+SDM4="

branches:
  only:
    - master
    - /^release.*$/
after_script:
  - ./fixup.sh
